### ISSUE TITLE
Finding microdeletions

### ISSUE THREAD

**Issue by GreeshmaThulasi** [CenterForMedicalGeneticsGhent/WisecondorX#35]
Hi,
I have data of patient with a known microdeletion (DiGeorge). The patient is mildly affected and is pregnant and hence done NIPT for finding the chance of Digeorge in their fetus. I have the cfDNA BAM file of 8 million reads. I tried to look at the microdeletion and got a z-score of -33.

**22	19000001	21400000**	-0.7799	**-33.09683751274384**
This is evident that there is a deletion at the desired location.

**_But my question is how to distinguish whether it is of maternal deletion or fetal deletion?_**

_Seeking your response
Greeshma Thulasi_

**Comment by leraman** [comment]
You can always make an educated guess based on the fetal DNA fraction. The certainty of this guess would increase with the fetal fraction. That being said, using sWGS data only, you can actually never be sure whether the fetus is affected for this microdeletion, since its maternal presence. In **theory**, you'll need an experimental procedure, like CVS or amniocentesis.

**Comment by GreeshmaThulasi** [comment]
Thanks for the reply. So the deletion or duplication of the fetus is predicted on the assumption that the mother is normal. Right?

**Comment by leraman** [comment]
With NIPT, yes.
