### ISSUE TITLE
Abnormal depth normalization in samples with high tumour content

### ISSUE THREAD

**Issue by ckrushton** [CenterForMedicalGeneticsGhent/WisecondorX#63]
I have been running WisecondorX and ichorCNA on 200+ samples with low-pass WGS data (0.15-0.3x coverage), using 500kb bins and a reference created from 68 samples. While WisecondorX is generally performing well, in samples with high levels of tumour DNA, WisecondorX seems to overall CNVs, especially in samples with widespread CNVs such as this example (corresponding ichorCNA results are on the bottom):
![image](https://user-images.githubusercontent.com/22357668/100169282-f3ba7080-2e77-11eb-9581-98d4d0ca1e43.png)

Is this behavior expected? Is there any way to avoid this issue? I would prefer not to set a unique Z-score threshold for each sample based upon tumour content if at all possible.

**Comment by leraman** [comment]
Hi @ckrushton 

Copy number detection tools that run on shallow whole-genome sequencing data provide 'relative' copy number alterations, meaning that the copy neutral state cannot be inferred with certainty. In WisecondorX, the neutral state is set as the median value, whereas in ichorCNA, it is predicted by a mathematical optimization algorithm. This is because the focus of WisecondorX is on data normalization, whereas the focus of ichorCNA is on tumor fraction prediction. If you feel ichorCNA predicts the copy neutral state accurately, you could move the log2 ratios of WisecondorX and use a simple ratio cutoff to call for aberrations.

Hope this helps,

Lennart

**Comment by ckrushton** [comment]
I will give that a shot. Thank you very much for the insightful response
