### ISSUE TITLE
NIPT how to find chrY aberrations?

### ISSUE THREAD

**Issue by rgiannico** [CenterForMedicalGeneticsGhent/WisecondorX#7]
Hi leraman, thank you for your amazing work on WisecondorX. 
I understand from the documentation and previous github issue conversations that for NIPT you suggest creating a reference from samples with normal female fetus only. Than to use this reference for testing both female and male fetus samples. 
This because if you use both male and female normal samples for the reference building process it causes chrX to be blacklisted (If I understand correctly it happens because wisecondorx will not be able to calculate a normal reference value for chrX because of the great variance between male and female chrX coverage values). 
But creating a female-only reference also means wisecondorx will never be able to find chrY aberrations (because the reference do not contain any chrY normal-reference information). 

So my question is: 
**How do you suggest I could try to predict chrY aberrations for NIPT samples? 
Is it a feature you are planning to add?** 

I'm not sure I fully understand the blacklisting issue, but I would like to try advancing some basic ideas anyway (I just hope they can be of some help). 
- Putative solution 1: Two references (1 for male and 1 for female): Do you think creating a normal-male sample reference (to test only male samples) and creating a normal-female sample reference (to test only female samples) could be a solution? 
- Putative solution 2: merging a chrYreference.npz with femalereference.npz: What about using a bunch of male reference bam files (normal male samples) and  crop only chrY reads from them (slice bam with chrY mapping reads only), use the sliced bam files to reate a chrYonly-reference.npz file, then finally merge it with the classic femaleonly-reference.npz file. How does it sounds to you? 

Thanks!

**Comment by leraman** [comment]
Hi @rgiannico,
I agree that the absence of a Y aberration prediction procedure for NIPT is indeed a shortcoming. The reason is kind of intrinsic to WisecondorX's approach: a blacklist is created based on the variability at each position, which is measured on a reference set. If let's say we create a male reference set (for NIPT this means male feti), than the Y chromosome will naturally be extremely variable compared to the autosomes, since the normalised number of reads at Y are fetal fraction depended -- indeed, all of the Y reads originate from the fetus, and non from the mother. For a non-NIPT male reference, this is not the case: healthy individuals are expected to have 1/2 of the reads at Y compared to any of the autosomes. Furthermore, for NIPT, this is not only a blacklisting issue: the ratio's are defined by 'observed read count/expected read count'. Since we don't know the expected read count, unless we know the fetal fraction, this can not be calculated accurately.
Concerning your second solution, we are planning to implement code for generating one reference in the future, created with male and female samples, each of which are gender annotated, resembling your suggestion. Yet this won't impact X/Y predictions.

**Comment by rgiannico** [comment]
Thank you very much for you answer, 
I'm sorry but I'm not sure if I can correctly extrapolate the answers to my questions:

- **Is it a feature you are planning to add?**
I do not understand if your answer is "No, because it's incompatible with the current wisecondorx strategy", or "Maybe in the future predicting the fetal fraction".  

- **How do you suggest I could try to predict chrY aberrations for NIPT samples?**
I understand your answer is basically "right now you can't using wisecondorX", and you think none of my putative solutions are applicable to try chrY aberration prediction for NIPT samples. So do you have any suggestions for me (or other users) facing the NIPT chrY aberrations prediction problem? Like try some other tool ; try implement some other strategy by myself (any idea?) ; or just wait for something you are going to implement for wisecondorx ? 

Thank you!

**Comment by leraman** [comment]
Hi @rgiannico,
I don't think this feature will be added in the near future, yet I do believe it is possible, but probably not using WCX's approach.
I'm not aware of any tool that accurately measures NIPT Y aberrations. You could try to implement it yourself, but will probably face a lot of difficulties: there are mostly very few Y reads using sWGS, the number of mappable positions is low at Y, there are numerous sequence similarities with X, reference Y levels will never be constant (this is the fetal fraction problem), etc ...
Best, Lennart
