### ISSUE TITLE
WisecondorX cannot identify and run .bam.gz after update

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/WisecondorX#77]
After the update, WisecondorX cannot run on .bam.gz. this is the log of error:

> [ERROR - 2021-04-01 14:27:13]: Unsupported input file type. Make sure your input filename has a correct extension (sam/bam/cram)

However, it run well on bgzip compressed .bam file if I remove .gz on file name

**Comment by matthdsm** [comment]
Hi @KhanhLPBao,
In the latest version we introduced a filename based check to look for the correct filetype, so it can be parsed accordingly.
As the error says, you file doesn't have a canonical extension (`.bam.gz` instead of `.bam`).
Since bam is essentially already bgzipped, it makes no sense to add the `.gz` extension, nor have I ever encountered it used that way.

The fact that your data is accepted if you remove your extension further proves that extra compression of your bam using `bgzip` has no effect on the data.

If you need smaller file sizes, you should try and use the `cram` format, which WiseCondorX now also accepts!

Kind regards
M
