### ISSUE TITLE
Wisecondor gender predicts all samples as females

### ISSUE THREAD

**Issue by smruti241** [CenterForMedicalGeneticsGhent/WisecondorX#80]
Hii,
I have run the command Wisecondor gender:
WisecondorX gender sample_006.npz reference_output.npz
And for every sample it gave as female. I have gone through some of the issues but I didnt get any result. Could you please tell me how to use this command? or I have to use some other files with this command. Thanks in advance

**Comment by KhanhLPBao** [comment]
Hi @smruti241 
I also meet the same problem many months ago. I believe this error is from the sample, not the program since it use the % of chromosome X to predict the gender. In my case I remove pseudo autosomal regions on both chromosome X and Y of .bam file before index it with samtools and run WisecondorX to make .npz file and it returned with 100% correct gender right now

**Comment by smruti241** [comment]
@KhanhLPBao  can you please provide me commands how did you used it? actually I am facing a lot of problems. Please send me the commands for predicting gender.

**Comment by smruti241** [comment]
Can you please tell me how did you remove pseudo autosomal regions on both chr X and Y of bam file?

**Comment by KhanhLPBao** [comment]
@smruti241 I go to https://genome.ucsc.edu/cgi-bin/hgTables, choose GrCH37 in my case. In group I choose "Mapping and Sequencing", table is "Problematic Region". The table contain pseudo-autosomal with some regions that cause problems are UCSC Unusual Region (I cannot check atm since UCSC is down or I cannot access to it, but its the first on the list with the name UCSC). In output choose bed file, then click "get output" to download it.
To filtered all sequences inside the region that listed on .bed file, use bedtools:
`bedtools intersect -abam sample.bam -b filter.bed -v > filtered.bam`

**Comment by smruti241** [comment]
@KhanhLPBao I did all the steps and finally ran WisecondorX gender. It is giving me all the samples as female. Now is it giving correct gender? before that I used this command:WisecondorX newref *.npz reference_output.npz --nipt --binsize 100000 --yfrac 1. I couldnt used --yfrac 0 becuase atleast 5 female feti samples should be there so put --yfrac 1. Please tell me now it is giving me gender as females, is it correct?

**Comment by KhanhLPBao** [comment]
@smruti241 on the description it says if you set --yfrac 0 its mean you want to treat all samples as female. On the other side you cannot set all samples as male alongside with --nipt tag. The program will automatically identify the cutoff value for gender if you not set --yfrac. Or if you want to set it manually but not know what value you should set, please use --plotyfrac plot.png to see the plot

**Comment by smruti241** [comment]
yeah I got you. I tried that and it worked, but in some cases it is not giving correct gender. But it is working now. Thank you
